#!/usr/bin/php
<?php

$cwd = getcwd();

$dir = realpath($argv[1]);

if (!is_dir($argv[1])) {
    die("pearify: no such file or directory $argv[1]\n");
}

chdir($dir);

ini_set('date.timezone', 'Europe/London');

$fileName = $dir . '/package.xml';

if (file_exists($fileName)) {
    unlink($fileName);
}

require_once 'PEAR/PackageFileManager2.php';
PEAR::setErrorHandling(PEAR_ERROR_DIE);

$summary = <<<EOT
Additional ZF tools specifically for use during Magento development.
EOT;
$description = <<<EOT
Additional ZF tools specifically for use during Magento development. Adding commands that will be useful during development with Magento. Command include: Clear cache, enable / disable cache and create admin user.
EOT;

if (!isset($argv[2])) {
    die("pearify: missing version\nusage: pearify [DIRECTORY] [VERSION] [STABILITY]\n");
}

$api = $argv[2];
$stability = isset($argv[3]) ? $argv[3] : '';
$version = $api . (!empty($stability) || $stability !== 'stable' ? $stability : '');

$notes = "-";

$package = new PEAR_PackageFileManager2();

$result = $package->setOptions(array(
    'filelistgenerator' => 'file',
    'changelogoldtonew' => true,
    'simpleoutput'      => true,
    'baseinstalldir'    => '/',
    'packagefile'       => 'package.xml',
    'packagedirectory'  => '.'));

if (PEAR::isError($result)) {
    echo $result->getMessage();
    die();
}

$package->setPackage('MageTool');
$package->setPackageType('php');
$package->setSummary($summary);
$package->setDescription($description);
$package->setChannel('pear.magetool.co.uk');
$package->setLicense('OSL 3.0', 'http://opensource.org/licenses/osl-3.0.php');
$package->setAPIVersion($api);
$package->setAPIStability($stability);
$package->setReleaseVersion($version);
$package->setReleaseStability($stability);
$package->setNotes($notes);
$package->setPhpDep('5.2.6');
$package->setPearinstallerDep('1.9.2');
$package->addMaintainer('lead', 'alistair.stead', 'Alistair Stead', 'alistair.stead@designdisclosure.com');
$package->addMaintainer('contributor', 'tonigrigoriu', 'Toni Grigoriu', 'tonigrigoriu@php.net');
$package->addIgnore(
    array(
        'bootstrap.php',
        'build/*',
        'package.xml',
        'pearize',
        'phpunit.xml',
        'README.markdown',
        'tests/*',
    )
);

$package->generateContents();

$result = $package->writePackageFile();
//$result = $package->debugPackageFile();

if (PEAR::isError($result)) {
    echo $result->getMessage();
    die();
}
